export enum DEPARTMENT {
  HR = 'HR',
  IT = 'IT',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
}

export enum ROLE {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  SUPPORT_STAFF = 'SUPPORT_STAFF',
}
export enum INTERACTION_TYPE {
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
}
export enum ASSET_CONDITION {
  NEW = 'NEW',
  USED = 'USED',
  BROKEN = 'BROKEN',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
}
export enum ASSET_TYPE {
  HARDWARE = 'HARDWARE',
  SOFTWARE = 'SOFTWARE',
  FURNITURE = 'FURNITURE',
}
export enum BOOKING_STATUS {
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}
export enum ANNOUNCEMENT_CATEGORY {
  GENERAL = 'GENERAL',
  HR = 'HR',
  IT = 'IT',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
}
export enum BOOKING_PATTERN {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}
export enum TICKET_STATUS {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  CLOSED = 'CLOSED',
}
export enum TICKET_CATEGORY {
  IT = 'IT',
  HR = 'HR',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
}