name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Docker Hub (or use AWS ECR login)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push Docker image
      - name: Build and Push Docker Image
        run: |
         
          docker build -t dacn .
          docker tag dacn ${{ secrets.DOCKERHUB_USERNAME }}/dacn:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dacn:latest

